### ISSUE TITLE
Scale3D failing if scaleZ is 1 for 3D images

### ISSUE THREAD

**Issue by andmccall** [imglib/imglib2-script#3]
I've been getting a consistent out of bounds exception when using Scale3D and a Z-scale value of 1 with 3D images. It works great for other scaleZ values I use (fractions between 0 and 1 to reduce the scale of the image), and a scaleZ of 1 works when using 2D images. I looked through the code a little bit, to try and figure out what was happening, and the only code block I could find (in AbstractAffine3D.java lines 191-195) that may affect things differently when scaleZ=1 was:

			if (Math.abs(m[10] - 1.0f) < 0.000001 && 0 == m[8] && 0 == m[9]) {
				long[] d = transform.getNewImageSize();
				d[2] = img.dimension(2); // 0-based: '2' is the third dimension
				transform.setNewImageSize(d);
			}

The only thing I could think of after looking at it is you may possibly need to set a new offset for the Z-dimension here as well. I'm pasting my error message from ImageJ below.

java.lang.ArrayIndexOutOfBoundsException: 1715350
	at net.imglib2.img.basictypeaccess.array.AbstractByteArray.getValue(AbstractByteArray.java:61)
	at net.imglib2.type.numeric.integer.GenericByteType.getByte(GenericByteType.java:127)
	at net.imglib2.type.numeric.integer.GenericByteType.set(GenericByteType.java:183)
	at net.imglib2.type.numeric.integer.GenericByteType.set(GenericByteType.java:51)
	at net.imglib2.interpolation.randomaccess.NLinearInterpolator.accumulate(NLinearInterpolator.java:264)
	at net.imglib2.interpolation.randomaccess.NLinearInterpolator.graycodeFwdRecursive(NLinearInterpolator.java:236)
	at net.imglib2.interpolation.randomaccess.NLinearInterpolator.get(NLinearInterpolator.java:205)
	at net.imglib2.interpolation.randomaccess.NLinearInterpolator.get(NLinearInterpolator.java:53)
	at net.imglib2.algorithm.transformation.ImageTransform.process(ImageTransform.java:219)
	at net.imglib2.script.algorithm.fn.AbstractAffine3D.processReal(AbstractAffine3D.java:200)
	at net.imglib2.script.algorithm.fn.AbstractAffine3D.process(AbstractAffine3D.java:123)
	at net.imglib2.script.algorithm.fn.AbstractAffine3D.<init>(AbstractAffine3D.java:74)
	at net.imglib2.script.algorithm.Affine3D.<init>(Affine3D.java:87)
	at net.imglib2.script.algorithm.Scale3D.<init>(Scale3D.java:67)
	at net.imglib2.script.algorithm.Scale3D.<init>(Scale3D.java:59)

**Comment by andmccall** [comment]
Nevermind, this is no longer happening for me, I think this was due to a small issue somewhere in my code.

**Comment by ctrueden** [comment]
Fixed by #4. Thanks @andmccall!

Please be aware that I am cutting a final 0.2.5 release of imglib2-script, and then we are retiring this component.
